api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : src
env_make   : ~
env_prep   : get-composer
env_post   : ci-coveralls,ci-codacy
php_conf   : timezone
php_exts   : igbinary
app_prep   : dep-composer
app_post   : ~
app_path   : ~
pkg_name   : wonka-bundle
pkg_desc   : "a collection of classes and interfaces aimed at facilitating Symfony bundle's, including helpers for advanced bundle configuration, kernel compiler passes, and more"
pkg_bndl   : false
