api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : src
env_make : ~
env_prep : get-composer
env_post : ci-coveralls,ci-codacy
php_conf : timezone
php_exts : igbinary
app_prep : dep-composer
app_post : ~
app_path : ~
pkg_name : wonka-bundle
pkg_desc : "a collection of objects, interfaces, and traits aimed at simplifying Symfony bundle setup and configuration. This includes helpers for defining advanced bundle config definitions, implementing kernel compiler passes, and much more."
pkg_bndl : true
