---

parameters :

    s.wonka.reflection_analyser.class                : SR\Wonka\Utility\Reflection\ClassReflectionAnalyser
    s.wonka.invokable_logger.class                   : SR\Wonka\Utility\Logger\InvokableLogger
    s.wonka.invokable_container_value_resolver.class : SR\WonkaBundle\Component\DependencyInjection\Container\InvokableContainerValueResolver

services :

    s.wonka.utility.reflection_analyser :
        alias : s.wonka.reflection_analyser

    s.wonka.utility.logger_callable :
        alias : s.wonka.invokable_logger

    s.wonka.utility.service_finder :
        alias : s.wonka.invokable_container_value_resolver

    s.wonka.reflection_analyser :
        class : %s.wonka.reflection_analyser.class%
        calls :
            - [ unsetReflectionClass ]

    s.wonka.invokable_logger :
        class     : %s.wonka.invokable_logger.class%
        arguments :
            - '@logger'

    s.wonka.invokable_container_value_resolver :
        class : %s.wonka.invokable_container_value_resolver.class%
        calls :
            - [ setContainer, [ '@service_container' ] ]

...
